name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_back:
    runs-on: windows-latest
    # Spécifie le répertoire de travail pour le back-end
    defaults:
      run:
        working-directory: ./back

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Build le projet et exécute les tests avec Maven
      - name: Build and test
        run: |
          mvn clean install
          mvn test

      # Commit du rapport de couverture
      - name: Commit coverage report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "ruiz.nico64@gmail.com"
          git add .
          git commit -m "Add JaCoCo coverage report"
          git push

